defaults:
  - env: hover        # Task
  - dynamics: a300    # Quadrotor Model
  - val: body_rates
  - _self_


# Control Mode
cm: ctbr              

device: "cuda"
dt: 0.01

num_envs: 1024
episodes: 15
steps: 800

truncation: 50

