defaults:
  - env: hover        # Task
  - dynamics: a300    # Quadrotor Model
  - renderer: replay
  - _self_


cm: ctbr              # Control Mode


device: "cuda"
dt: 0.01

num_envs: 1024
episodes: 15
steps: 800

truncation: 50

