defaults:
  - env: hover
  - dynamics: quadrotor
  - renderer: replay
  - controller: proportional_derivative
  - _self_



device: "cuda"
dt: 0.01


num_envs: 2048
episodes: 30
steps: 500

truncation: 100


