defaults:
  - env: hover
  - dynamics: quadrotor
  - renderer: replay
  - controller: proportional_derivative
  - _self_



device: "cuda"
dt: 0.01

num_envs: 2048
episodes: 50
steps: 1000
truncation: 100

lr: 1e-3
