name: geometric
abbr: geo

encoder: [7, 16, 16, 3]
policy: [19, 128, 128, 4]

# policy: [19, 128, 128, 5] # for the geometric controller collective thrust + quaternions = 5

lr: 1e-3


loss_weights:
  pos: 2.0
  vel: 1.0
  att: 0.2
  body_rates: 0.1


rand_fourier:
  num_harmonics: 3  # must be integer
  z_offset: 2.0
  A: 1.0
  w: 1.0
  phi: 2.0


max_dist_to_target: 10.0

max_TTWR: 2.0

track_path: "/home/adame/torchAirBender/miscellaneous/race_tracks/a2rl-s2.yaml"
trajectory_path: "/home/adame/torchAirBender/miscellaneous/trajectories/TOGT/togt_a2rl-s2.csv"