name: racing

# nn: [16, 128, 128, 128, 4]
# nn: [16, 64, 64, 64, 4]
nn: [16, 128, 128, 4]
lr: 1e-3

loss_weights:
  pos: 1.5
  vel: 0.5
  att: 0.1
  body_rates: 0.005

termination_penalty: 0.0

traj:
  num_harmonics: 2  # must be integer
  z_offset: 2.0
  A: 1.0
  w: 1.0
  phi: 2.0

max_dist_to_target: 3.5

load_traj: True
test_traj: "/home/adame/torchAirBender/miscellaneous/trajectories/TOGT/aos_togt_traj.csv"


max_mass_norm_thrust: 3.5