name: trajectory_tracking
abbr: tt

policy: [21, 128, 128]   # only input and hidden layers

lr: 1e-3

loss_weights:
  pos: 2.0
  vel: 1.0
  att: 0.2
  body_rates: 0.2


traj:
  num_harmonics: 3  
  z_offset: 3.0
  A: 1.0
  w: 3.0
  phi: 2.0
  dt: 0.01

max_dist_to_target: 5.0
rmse_threshold: 0.15


w_increase: 0.0

# # For the CTBR controller
kp_rate: 0.2
w_max: 5.0