name: tt_plus_am
abbr: ttpam

encoder: [7, 16, 16, 3]
policy: [16, 128, 128]   # only input and hidden layers
# policy: [16, 128, 128, 128]   # only input and hidden layers


lr: 1e-3


loss_weights:
  pos: 2.0
  vel: 1.0
  att: 0.2
  body_rates: 0.5


traj:
  num_harmonics: 3  # must be integer
  z_offset: 2.0
  A: 1.0
  w: 1.0
  phi: 2.0
  dt: ${dt}



max_dist_to_target: 5.0
rmse_threshold: 0.15

w_increase: 0.05

# max_TWR: 2.0

# # For the CTBR controller
kp_rate: 1.0
w_max: 0.5